import Head from 'next/head'
import TitleSection from './home/TitleContainer/TitleSection'
import FetchSection from './home/FetchContainer/FetchSection'
import { GetStaticProps, GetStaticPropsResult } from 'next'
import { SWRConfig } from 'swr'
import { fetchAPI } from './home/FetchContainer/_data/fetchAPI'
import { xWingAscii } from '@public/asciiArt/x-wing'

// Fetch should add to the url under /data/[subject]/[id]#APISearch

export default function HomePage({ fallback }: { fallback: FallbackProps }) {
  if (process.env.NODE_ENV === 'production') console.log(xWingAscii())
  return (
    <>
      <Head>
        <title>Holocron.io</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <TitleSection />
      <SWRConfig value={{ fallback }}>
        <FetchSection />
      </SWRConfig>
    </>
  )
}

interface FallbackProps {
  fallback: { 'https://swapi.dev/api/people/1/': string }
}

/// Fetches the example API request on the server to save client resources
/// Data cached for 24 hours
export const getStaticProps: GetStaticProps<FallbackProps> = async (): Promise<
  GetStaticPropsResult<FallbackProps>
> => {
  const data = await fetchAPI('https://swapi.dev/api/people/1/')

  // You can see this data in the browser console, sent in the HTML under the tag:
  // <script id="__NEXT_DATA__" type="application/json">...</script>
  return {
    props: { fallback: { 'https://swapi.dev/api/people/1/': data } },
    revalidate: 60 * 60 * 24,
  }
}
