name: Code Formatting

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  eslint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run eslint
        run: pnpm next lint

  stylelint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run stylelint
        run: pnpm lint:styles

  prettier:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run prettier
        run: pnpm prettier --check .
